IMPORTING THE DATA

In [2]:
import pandas as pd
df=pd.read_csv("Telecom_customer_churn.csv")
print (df)

      customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1   
1     5575-GNVDE    Male              0      No         No      34   
2     3668-QPYBK    Male              0      No         No       2   
3     7795-CFOCW    Male              0      No         No      45   
4     9237-HQITU  Female              0      No         No       2   
...          ...     ...            ...     ...        ...     ...   
7038  6840-RESVB    Male              0     Yes        Yes      24   
7039  2234-XADUH  Female              0     Yes        Yes      72   
7040  4801-JZAZL  Female              0     Yes        Yes      11   
7041  8361-LTMKD    Male              1     Yes         No       4   
7042  3186-AJIEK    Male              0      No         No      66   

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0              No  No phone service             DSL             No  ...   
1        

In [3]:
df.head(10)

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   
5  9305-CDSKC  Female              0      No         No       8          Yes   
6  1452-KIOVK    Male              0      No        Yes      22          Yes   
7  6713-OKOMC  Female              0      No         No      10           No   
8  7892-POOKP  Female              0     Yes         No      28          Yes   
9  6388-TABGU    Male              0      No        Yes      62          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   
5               Yes     Fiber optic             No  ...              Yes   
6               Yes     Fiber optic             No  ...               No   
7  No phone service             DSL            Yes  ...               No   
8               Yes     Fiber optic             No  ...              Yes   
9                No             DSL            Yes  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   
5          No         Yes             Yes  Month-to-month              Yes   
6          No         Yes              No  Month-to-month              Yes   
7          No          No              No  Month-to-month               No   
8         Yes         Yes             Yes  Month-to-month              Yes   
9          No          No              No        One year               No   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  
5           Electronic check          99.65         820.5   Yes  
6    Credit card (automatic)          89.10        1949.4    No  
7               Mailed check          29.75         301.9    No  
8           Electronic check         104.80       3046.05   Yes  
9  Bank transfer (automatic)          56.15       3487.95    No  

[10 rows x 21 columns]

In [4]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [5]:
import numpy as np
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

No null values

FEATURE ENGINEERING

In [6]:
df['TotalCharges'].value_counts()

           11
20.2       11
19.75       9
20.05       8
19.9        8
           ..
419.4       1
387.7       1
1948.35     1
1663.5      1
54.3        1
Name: TotalCharges, Length: 6531, dtype: int64

In [7]:
df['TotalCharges'].isnull().sum()

0

In [8]:
df=df.drop(['TotalCharges'],axis=1)

In [9]:
df['Contract1']=df['Contract'].str.split('-').str[0]
df['Contract2']=df['Contract'].str.split('-').str[1]
df['Contract3']=df['Contract'].str.split('-').str[2]

In [10]:
df=df.drop(['Contract'],axis=1)
df=df.drop(['Contract2'],axis=1)
df=df.drop(['Contract3'],axis=1)

In [11]:
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity OnlineBackup  \
0  No phone service             DSL             No          Yes   
1                No             DSL            Yes           No   
2                No             DSL            Yes          Yes   
3  No phone service             DSL            Yes           No   
4                No     Fiber optic             No           No   

  DeviceProtection TechSupport StreamingTV StreamingMovies PaperlessBilling  \
0               No          No          No              No              Yes   
1              Yes          No          No              No               No   
2               No          No          No              No              Yes   
3              Yes         Yes          No              No               No   
4               No          No          No              No              Yes   

               PaymentMethod  MonthlyCharges Churn Contract1  
0           Electronic check           29.85    No     Month  
1               Mailed check           56.95    No  One year  
2               Mailed check           53.85   Yes     Month  
3  Bank transfer (automatic)           42.30    No  One year  
4           Electronic check           70.70   Yes     Month

In [12]:
df['PaymentMethod1']=df['PaymentMethod'].str.split('(automatic)').str[0]
df['PaymentMethod2']=df['PaymentMethod'].str.split('(automatic)').str[1]

In [13]:
df=df.drop(['PaymentMethod'],axis=1)
df=df.drop(['PaymentMethod2'],axis=1)

In [14]:
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity OnlineBackup  \
0  No phone service             DSL             No          Yes   
1                No             DSL            Yes           No   
2                No             DSL            Yes          Yes   
3  No phone service             DSL            Yes           No   
4                No     Fiber optic             No           No   

  DeviceProtection TechSupport StreamingTV StreamingMovies PaperlessBilling  \
0               No          No          No              No              Yes   
1              Yes          No          No              No               No   
2               No          No          No              No              Yes   
3              Yes         Yes          No              No               No   
4               No          No          No              No              Yes   

   MonthlyCharges Churn Contract1    PaymentMethod1  
0           29.85    No     Month  Electronic check  
1           56.95    No  One year      Mailed check  
2           53.85   Yes     Month      Mailed check  
3           42.30    No  One year   Bank transfer (  
4           70.70   Yes     Month  Electronic check

In [15]:
df['PaymentMethod2']=df['PaymentMethod1'].str.split('(').str[0]
df['PaymentMethod3']=df['PaymentMethod1'].str.split('(').str[0]

In [16]:
df=df.drop(['PaymentMethod1'],axis=1)
df=df.drop(['PaymentMethod3'],axis=1)

In [17]:
df['customerID1']=df['customerID'].str.split('-').str[0]
df['customerID2']=df['customerID'].str.split('-').str[1]

In [18]:
df['customerID1']=df['customerID1'].astype(int)

In [19]:
df=df.drop(['customerID'],axis=1)

In [20]:
df.head()

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  Female              0     Yes         No       1           No   
1    Male              0      No         No      34          Yes   
2    Male              0      No         No       2          Yes   
3    Male              0      No         No      45           No   
4  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity OnlineBackup  ...  \
0  No phone service             DSL             No          Yes  ...   
1                No             DSL            Yes           No  ...   
2                No             DSL            Yes          Yes  ...   
3  No phone service             DSL            Yes           No  ...   
4                No     Fiber optic             No           No  ...   

  TechSupport StreamingTV StreamingMovies PaperlessBilling MonthlyCharges  \
0          No          No              No              Yes          29.85   
1          No          No              No               No          56.95   
2          No          No              No              Yes          53.85   
3         Yes          No              No               No          42.30   
4          No          No              No              Yes          70.70   

   Churn Contract1    PaymentMethod2 customerID1  customerID2  
0     No     Month  Electronic check        7590        VHVEG  
1     No  One year      Mailed check        5575        GNVDE  
2    Yes     Month      Mailed check        3668        QPYBK  
3     No  One year    Bank transfer         7795        CFOCW  
4    Yes     Month  Electronic check        9237        HQITU  

[5 rows x 21 columns]

In [21]:
from sklearn.preprocessing import LabelEncoder
LE=LabelEncoder()
df["gender"]=LE.fit_transform(df['gender'])
df["Partner"]=LE.fit_transform(df['Partner'])
df["Dependents"]=LE.fit_transform(df['Dependents'])
df["PhoneService"]=LE.fit_transform(df['PhoneService'])

In [22]:
from sklearn.preprocessing import LabelEncoder
LE=LabelEncoder()
df["MultipleLines"]=LE.fit_transform(df['MultipleLines'])
df["InternetService "]=LE.fit_transform(df['InternetService'])
df["OnlineSecurity"]=LE.fit_transform(df['OnlineSecurity'])
df["OnlineBackup"]=LE.fit_transform(df['OnlineBackup'])
df["DeviceProtection"]=LE.fit_transform(df['DeviceProtection'])

df["TechSupport"]=LE.fit_transform(df['TechSupport'])
df["StreamingTV"]=LE.fit_transform(df['StreamingTV'])
df["StreamingMovies"]=LE.fit_transform(df['StreamingMovies'])

In [23]:
from sklearn.preprocessing import LabelEncoder
LE=LabelEncoder()
df["PaperlessBilling"]=LE.fit_transform(df['PaperlessBilling'])
df["Churn"]=LE.fit_transform(df['Churn'])

df["Contract1"]=LE.fit_transform(df['Contract1'])
df["customerID2"]=LE.fit_transform(df['customerID2'])
df["PaymentMethod2"]=LE.fit_transform(df['PaymentMethod2'])
df["InternetService"]=LE.fit_transform(df['InternetService'])

In [24]:
df.head()

gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0       0              0        1           0       1             0   
1       1              0        0           0      34             1   
2       1              0        0           0       2             1   
3       1              0        0           0      45             0   
4       0              0        0           0       2             1   

   MultipleLines  InternetService  OnlineSecurity  OnlineBackup  ...  \
0              1                0               0             2  ...   
1              0                0               2             0  ...   
2              0                0               2             2  ...   
3              1                0               2             0  ...   
4              0                1               0             0  ...   

   StreamingTV  StreamingMovies  PaperlessBilling  MonthlyCharges  Churn  \
0            0                0                 1           29.85      0   
1            0                0                 0           56.95      0   
2            0                0                 1           53.85      1   
3            0                0                 0           42.30      0   
4            0                0                 1           70.70      1   

   Contract1  PaymentMethod2  customerID1  customerID2  InternetService   
0          0               2         7590         5824                 0  
1          1               3         5575         1874                 0  
2          0               3         3668         4577                 0  
3          1               0         7795          651                 0  
4          0               2         9237         2191                 1  

[5 rows x 22 columns]

In [25]:
df.dtypes

gender                int32
SeniorCitizen         int64
Partner               int32
Dependents            int32
tenure                int64
PhoneService          int32
MultipleLines         int32
InternetService       int32
OnlineSecurity        int32
OnlineBackup          int32
DeviceProtection      int32
TechSupport           int32
StreamingTV           int32
StreamingMovies       int32
PaperlessBilling      int32
MonthlyCharges      float64
Churn                 int32
Contract1             int32
PaymentMethod2        int32
customerID1           int32
customerID2           int32
InternetService       int32
dtype: object

SPILTTING INTO X AND Y

In [26]:
x=df.drop("Churn",axis=1)
y=df["Churn"]
x.head()

gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0       0              0        1           0       1             0   
1       1              0        0           0      34             1   
2       1              0        0           0       2             1   
3       1              0        0           0      45             0   
4       0              0        0           0       2             1   

   MultipleLines  InternetService  OnlineSecurity  OnlineBackup  ...  \
0              1                0               0             2  ...   
1              0                0               2             0  ...   
2              0                0               2             2  ...   
3              1                0               2             0  ...   
4              0                1               0             0  ...   

   TechSupport  StreamingTV  StreamingMovies  PaperlessBilling  \
0            0            0                0                 1   
1            0            0                0                 0   
2            0            0                0                 1   
3            2            0                0                 0   
4            0            0                0                 1   

   MonthlyCharges  Contract1  PaymentMethod2  customerID1  customerID2  \
0           29.85          0               2         7590         5824   
1           56.95          1               3         5575         1874   
2           53.85          0               3         3668         4577   
3           42.30          1               0         7795          651   
4           70.70          0               2         9237         2191   

   InternetService   
0                 0  
1                 0  
2                 0  
3                 0  
4                 1  

[5 rows x 21 columns]

SCALING

In [27]:
from sklearn.preprocessing import MinMaxScaler
mms=MinMaxScaler()
scaled = mms.fit_transform(df)
print(scaled)

[[0.         0.         1.         ... 0.75933153 0.82739025 0.        ]
 [1.         0.         0.         ... 0.55769038 0.266231   0.        ]
 [1.         0.         0.         ... 0.3668568  0.65023441 0.        ]
 ...
 [0.         0.         1.         ... 0.48023617 0.40417673 0.        ]
 [1.         1.         1.         ... 0.83648554 0.46654354 0.5       ]
 [1.         0.         0.         ... 0.31862304 0.0136383  0.5       ]]


BUILDING MODEL

In [28]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=0) 

RANDOM FOREST

In [29]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [30]:
y_pred = classifier.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [31]:
from sklearn import metrics
print('The accuracy of Random Forest Classification is: ', metrics.accuracy_score(y_pred, y_test))

The accuracy of Random Forest Classification is:  0.781505376344086


In [32]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [33]:
cm 

array([[1542,  170],
       [ 338,  275]], dtype=int64)

SVC

In [34]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(x_train, y_train)

SVC(kernel='linear', random_state=0)

In [36]:
y_pred = classifier.predict(x_test)
y_pred

array([0, 1, 0, ..., 0, 1, 0])

In [37]:
from sklearn import metrics
print('The accuracy of svc is: ', metrics.accuracy_score(y_pred, y_test))

The accuracy of svc is:  0.7174193548387097


In [38]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [39]:
cm

array([[1347,  365],
       [ 292,  321]], dtype=int64)

DTC

In [42]:
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [43]:
y_pred = classifier.predict(x_test)
y_pred

array([0, 1, 0, ..., 0, 1, 0])

In [44]:
from sklearn import metrics
print('The accuracy of DTC is: ', metrics.accuracy_score(y_pred, y_test))

The accuracy of DTC is:  0.7174193548387097


In [45]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [46]:
cm

array([[1347,  365],
       [ 292,  321]], dtype=int64)

In [ ]:
Random forest is the best model with accuracy 78%